### ISSUE TITLE
Growatt DB9 (RS2329) pinout

### ISSUE THREAD

**Issue by pfirtelu** [lemval/growatt-rs232-reader#1]
Hey lemval, Thanks for your library!
As you might know there are Growatt adapters which you can plug to DB9 to add functions (wifi, lan, bluetooth, ...).
I would like to use your library on eg. an Arduino and use the power provided by the inverter DB9 connector to power the Arduino so no external power source is required. Do you know per chance how many current you can draw from inverter DB9 connector to power the reader electronics? Thanks for the hint!

**Comment by lemval** [comment]
Hi pfirtelu!

Glad to be helpful!

No such luck finding any information in the Growatt documentation I have. Although it isn't much by standards. Check http://www.ti.com/lit/an/snla037b/snla037b.pdf, page 7. You can try increasing the load mA by mA and see the voltage drop by using a voltage meter and some resistors presumably.

**Comment by lemval** [comment]
Closed due to inactivity.
