### ISSUE TITLE
Growatt Protocol Specs

### ISSUE THREAD

**Issue by 3s1d** [lemval/growatt-rs232-reader#2]
Hi,
could your please share the document of the protocol specifications. So far, I only was able to find 'Growatt Inverter Communication Command' (from 2010) specs which you might use? I'd like to change/write some internal values. Do you know how it's done? ShineBus does not work for me (Windows in Parallels on Mac... this could be the issue...)

Thanks in advance!
Juergen

**Comment by Wilm0r** [comment]
You mean https://www.snafu.priv.at/mystuff/growatt-proto.pdf I suppose?

The init byte sequence in there appears to match what this code does at least.

**Comment by lemval** [comment]
Closed due to inactivity.
