### ISSUE TITLE
Should a Growatt 3000-MTL-S be supported?

### ISSUE THREAD

**Issue by skinkie** [lemval/growatt-rs232-reader#3]
I am trying multiple open source packages on a Growatt 3000-MTL-S that was connected via a ShineLAN before. My main purpose for this attempt is to have an increased samplerate for the reactive voltage and network frequency. Basically none of packages including this one worked. Has this ever be tested with the MTL-S series?

**Comment by lemval** [comment]
Hi @skinkie, I only run a model 2000 so I do not know.

Is a comm port assigned (see http://www.growatt.co.nl/upload/file/contents/2019/06/5d021f3dd2370.pdf page 25)?
Can you get a connection using ShineNet (as that is suggested in that manual):

Users are able to monitor the inverter after the setting of software. Detailed information about setting and functions refer
to the ShineNET Manual. You can download ShineNet from:ftp://113.106.58.169, the user name is ftpguest and Password is ftpguest.

**Comment by lemval** [comment]
Closed due to inactivity.
