### ISSUE TITLE
Doesn't work with Growatt 3000 S

### ISSUE THREAD

**Issue by timwegenerDE** [lemval/growatt-rs232-reader#4]
Hi there,

when I start the reader I get an error:

15:18 [INFO] Starting Growatt Inverter Reader v1.100
15:18 [INFO] Init requested...
15:18 [INFO] Sending initialisation to inverter...
15:18 [WARN] Init not accepted: EOF
15:18 [WARN] Failed. Please retry!

It's an Growatt 3000 S.

**Comment by lemval** [comment]
Hi @timwegenerDE, I've never tested with the 3000 model. Is a comm port assigned (see http://www.growatt.co.nl/upload/file/contents/2019/06/5d021f3dd2370.pdf page 25)?
Can you get a connection using ShineNet (as that is suggested in that manual):

Users are able to monitor the inverter after the setting of software. Detailed information about setting and functions refer
to the ShineNET Manual. You can download ShineNet from:ftp://113.106.58.169, the user name is ftpguest and Password is ftpguest.

**Comment by lemval** [comment]
Closed due to inactivity.
