### ISSUE TITLE
Growatt SPH series

### ISSUE THREAD

**Issue by sandervandegeijn** [lemval/growatt-rs232-reader#5]
I'm looking at the possibilities of using a Growatt SPH series inverter which supports feeding power back to the grid from a battery. Would it be possible to change the mode/times/maybe even output power through RS-232? This would make the inverter perfect for DIY battery builds :)

I haven't found new protocol documentation on Google but maybe I have overlooked some stuff.

**Comment by lemval** [comment]
Only manual I could find is:
- http://www.snafu.priv.at/mystuff/growatt-proto.pdf
- copy here: https://github.com/SteveNew/GrowattRpi/raw/master/growatt-proto.pdf
Would love to get an updated manual though...

This document only describes one single write command for setting parameters, but that is limited to reset, test, language and contrast as it seems. You could try to write other values (with possible risk of bricking the device).

**Comment by lemval** [comment]
Closed due to inactivity.
